title: Predicting Political Affiliations of Social Media Users
description: A project exploring the use of machine learning and large language models to predict political affiliations based on social media activity.
# show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
